# Generated by Django 5.2.7 on 2025-10-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0004_remove_customuser_groups_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
