# Generated by Django 4.2.25 on 2026-02-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_desc_en_news_slug_news_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
